### ISSUE TITLE
django-jsonfield==1.0.1 incompatible with Django2.1

### ISSUE THREAD

**Issue by Drahflow** [adamchainz/gargoyle#209]
https://bitbucket.org/schinckel/django-jsonfield/issues/63/jsonwidgetrender-does-not-accept-renderer

And from the Django docs:
https://docs.djangoproject.com/en/2.0/ref/forms/widgets/#django.forms.Widget.render
> The renderer argument was added. Support for subclasses that don’t accept it will be removed in Django 2.1.

... and indeed it was.

**Comment by adamchainz** [comment]
I'm afraid this is an upstream issue in django-jsonfield, I don't think we can do much here apart from wait for the latest version there?

**Comment by Drahflow** [comment]
I wouldn't hold by breath, last commit (https://bitbucket.org/schinckel/django-jsonfield/commits/all) is from 2017-05-29; issue to django-jsonfield was reported on 2018-01-11.

I notified the maintainer per mail, let's hope for the best :)

**Comment by adamchainz** [comment]
If it's really blocking and there's a workaround we can do here, e.g. disabling the widget, we can consider that. But ideally it should be fixed upstream.

**Comment by Drahflow** [comment]
I prepared the (trivial) PR: https://bitbucket.org/schinckel/django-jsonfield/pull-requests/38/accept-renderer-kwarg-fix-issue-63/diff

**Comment by adamchainz** [comment]
I've just gotten round to taking over django-jsonfield and pushing it. Thanks for your contribution and patience! The repo for django-jsonfield is now at https://github.com/adamchainz/django-jsonfield . It needs some more work to make it easy to maintain but it's functional for now!

Hope that helps you out,

Adam
