### ISSUE TITLE
Lag in changes taking effect?

### ISSUE THREAD

**Issue by benjiwheeler** [adamchainz/gargoyle#244]
Using gargoyle with Django, we've noticed a lag in the changes taking effect -- from 5 minutes to more than 20. It's unclear if this is due to settings being applied on top of gargoyle (memcached, etc.) or what.

Thoughts or suggestions welcome!

**Comment by adamchainz** [comment]
You're a couple years too late, this project is no longer maintained as per the change log note. I'm going to archive the repo now.
